apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      env: test
  template:
    metadata:
      labels:
        app: mysql
        env: test
    spec:
      # Test node'unda çalışması için
      nodeSelector:
        node-role: test
      # Pod Anti-Affinity kısmını geçici olarak kaldıralım (sorun çıkarabilir)
      # affinity:
      #   podAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - wordpress
      #       topologyKey: kubernetes.io/hostname
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        args:
        - "--default-authentication-plugin=mysql_native_password"
        - "--skip-log-bin"
        # Aşağıdaki satırları EKLEYİN
        - "--innodb-buffer-pool-size=256M"
        - "--innodb-log-file-size=64M"
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
          limits:
            memory: 2Gi
            cpu: 500m
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 120  # 60'tan 120'ye çıkarın
          periodSeconds: 20
          timeoutSeconds: 10
          failureThreshold: 5       # 3'ten 5'e çıkarın

        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
          initialDelaySeconds: 60   # 30'dan 60'a çıkarın
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5       # 3'ten 5'e çıkarın
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc