# secrets.yaml - Hassas bilgiler burada saklanır
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: test
type: Opaque
data:
  # Password: mysqlpassword123 (base64 encoded halini vercez)
  mysql-root-password: bXlzcWxwYXNzd29yZDEyMw==
  mysql-password: d29yZHByZXNzcGFzczEyMw==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: production
type: Opaque
data:
  # Production için farklı şifreler vercez
  mysql-root-password: cHJvZG15c3FscGFzczQ1Ng==
  mysql-password: cHJvZHdvcmRwcmVzczc4OQ==