# secrets.yaml - Test ve Production için MySQL secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: test
type: Opaque
data:
  mysql-root-password: bXlzcWxwYXNzd29yZDEyMw==  # mysqlpassword123
  mysql-password: d29yZHByZXNzcGFzczEyMw==        # wordpresspass123
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: production
type: Opaque
data:
  mysql-root-password: cHJvZG15c3FscGFzczQ1Ng==   # prodmyqslpass456
  mysql-password: cHJvZHdvcmRwcmVzczc4OQ==        # prodwordpresspass789